import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { NgExample } from './ngExample';

const routes: Routes = [
  { path: 'src001', component: AngularExample[1] },
  { path: 'src002', component: AngularExample[2] },
  { path: 'src003', component: AngularExample[3] },
  { path: 'src004', component: AngularExample[4] },
  { path: 'src005', component: AngularExample[5] },
  { path: 'src006', component: AngularExample[6] },
  { path: 'src007', component: AngularExample[7] },
  { path: 'src008', component: AngularExample[8] },
  { path: 'src009', component: AngularExample[9] },
  { path: 'src010', component: AngularExample[10] },
  { path: 'src011', component: AngularExample[11] },
  { path: 'src012', component: AngularExample[12] },
  { path: 'src013', component: AngularExample[13] },
  { path: 'src014', component: AngularExample[14] },
  { path: 'src015', component: AngularExample[15] },
  { path: 'src016', component: AngularExample[16] },
  { path: 'src017', component: AngularExample[17] },
  { path: 'src018', component: AngularExample[18] },
  { path: 'src019', component: AngularExample[19] },
  { path: 'src020', component: AngularExample[20] },
  { path: 'src021', component: AngularExample[21] },
  { path: 'src022', component: AngularExample[22] },
  { path: 'src023', component: AngularExample[23] },
  { path: 'src024', component: AngularExample[24] },
  { path: 'src025', component: AngularExample[25] },
  { path: 'src026', component: AngularExample[26] },
  { path: 'src027', component: AngularExample[27] },
  { path: 'src028', component: AngularExample[28] },
  { path: 'src029', component: AngularExample[29] },
  { path: 'src030', component: AngularExample[30] },
  { path: 'src031', component: AngularExample[31] },
  { path: 'src032', component: AngularExample[32] },
  { path: 'src033', component: AngularExample[33] },
  { path: 'src034', component: AngularExample[34] },
  { path: 'src035', component: AngularExample[35] },
  { path: 'src036', component: AngularExample[36] },
  { path: 'src037', component: AngularExample[37] },
  { path: 'src038', component: AngularExample[38] },
  { path: 'src039', component: AngularExample[39] },
  { path: 'src040', component: AngularExample[40] },
  { path: 'src041', component: AngularExample[41] },
  { path: 'src042', component: AngularExample[42] },
  { path: 'src043', component: AngularExample[43] },
  { path: 'src044', component: AngularExample[44] },
  { path: 'src045', component: AngularExample[45] },
  { path: 'src046', component: AngularExample[46] },
  { path: 'src047', component: AngularExample[47] },
  { path: 'src056', component: AngularExample[56] },
  { path: 'src057', component: AngularExample[57] },
  { path: 'src058', component: AngularExample[58] },
  { path: 'src059', component: AngularExample[59] },
  { path: 'src060', component: AngularExample[60] },
  { path: 'src061', component: AngularExample[61] },
  { path: 'src062', component: AngularExample[62] },
  { path: 'src063', component: AngularExample[63] },
  { path: 'src064', component: AngularExample[64] },
  { path: 'src065', component: AngularExample[65] },
  { path: 'src066', component: AngularExample[66] },
  { path: 'src067', component: AngularExample[67] },
  { path: 'src068', component: AngularExample[68] },
  { path: 'src069', component: AngularExample[69] },
  { path: 'src070', component: AngularExample[70] },
  { path: 'src071', component: AngularExample[71] },
  { path: 'src072', component: AngularExample[72] },
  { path: 'src073', component: AngularExample[73] },
  { path: 'src074', component: AngularExample[74] },
  { path: 'src075', component: AngularExample[75] },
  { path: 'src076', component: AngularExample[76] },
  { path: 'src077', component: AngularExample[77] },
  { path: 'src078', component: AngularExample[78] },
  { path: 'src079', component: AngularExample[79] },
  { path: 'src080', component: AngularExample[80] },
  { path: 'src081', component: AngularExample[81] },
  { path: 'src082', component: AngularExample[82] },
  { path: 'src083', component: AngularExample[83] },
  { path: 'src084', component: AngularExample[84] },
  { path: 'src085', component: AngularExample[85] },
  { path: 'src086', component: AngularExample[86] },
  { path: 'src087', component: AngularExample[87] },
  { path: 'src088', component: AngularExample[88] },
  { path: 'src089', component: AngularExample[89] },
  { path: 'src090', component: AngularExample[90] },
  { path: 'src091', component: AngularExample[91] },
  { path: 'src092', component: AngularExample[92] },
  { path: 'src093', component: AngularExample[93] },
  { path: 'src094', component: AngularExample[94] },
  { path: 'src095', component: AngularExample[95] },
  { path: 'src096', component: AngularExample[96] },
  { path: 'src097', component: AngularExample[97] },
  { path: 'src098', component: AngularExample[98] },
  { path: 'src099', component: AngularExample[99] },
  { path: 'src100', component: AngularExample[100] },
  { path: 'src101', component: AngularExample[101] },
  { path: 'src102', component: AngularExample[102] },
  { path: 'src103', component: AngularExample[103] },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
})
export class PrimeFlexRoutingModule {}
